---
apiVersion: v1
kind: Deployment
metadata: 
  name: backend
namespace: test
# labels of deployment rsource
labels:
  app: backend
  tier: backend
  project: expence
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expence
template:
  metadata:
    labels:
      app: backend
      tier: backend
      project: expence
  spec:
    containers:
    - name: nginx
      image: joindevops/backend:1.1.0

---
apiVersion: v1
kind: Service
metadata:
 name: backend # if we did not give any type of service it will take by default as clusterIP
spec:
  selector: # labels are used as selectors
    app: backend
    tier: backend
    project: expence
  ports:
  -  protocol: TCP
     port: 8080 # service port
     targetPort: 8080 # backend port madatory

