---
apiVersion: v1
kind: Deployment
metadata: 
  name: mysql
namespace: test
# labels of deployment rsource
labels:
  app: mysql
  tier: mysql
  project: expence
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expence
template:
  metadata:
    labels:
      app: mysql
      tier: mysql
      project: expence
  spec:
    containers:
    - name: nginx
      image: joindevops/mysql:1.0.0

---
apiVersion: v1
kind: Service
metadata:
 name: mysql # if we did not give any type of service it will take by default as clusterIP
spec:
  selector: # labels are used as selectors
    app: mysql
    tier: mysql
    project: expence
  ports:
  -  protocol: TCP
     port: 3306 # service port
     targetPort: 3306 # sql port - madatory

